name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} \
          echo "✅ SSH connected"

      - name: Deploy to VPS via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/nodetest/nodetest
            git pull
          EOF
      - name: Send ntfy Notification
        run: |
          curl -H "Title: 🚀 EZCart Deployment" \
           -H "Priority: high" \
           -d "✅ Deployment completed successfully with Git pull, PM2 restart, and Nginx reload." \
            https://ntfy.sh/deployment
